spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa